"""Add user roles and registration codes

Revision ID: 20d944622c86
Revises: 47a39df5f687
Create Date: 2025-11-19 14:18:30.478870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d944622c86'
down_revision: Union[str, None] = '47a39df5f687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('email_restriction', sa.String(length=255), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('used_by_user_id', sa.UUID(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_registration_codes_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], name=op.f('fk_registration_codes_used_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_codes'))
    )
    op.create_index(op.f('ix_registration_codes_code'), 'registration_codes', ['code'], unique=True)
    op.create_index(op.f('ix_registration_codes_email_restriction'), 'registration_codes', ['email_restriction'], unique=False)

    # Add role column as nullable first
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=True))

    # Update existing users to have 'teacher' role
    op.execute("UPDATE users SET role = 'teacher' WHERE role IS NULL")

    # Now make the column not nullable
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_registration_codes_email_restriction'), table_name='registration_codes')
    op.drop_index(op.f('ix_registration_codes_code'), table_name='registration_codes')
    op.drop_table('registration_codes')
    # ### end Alembic commands ###
