"""make email_restriction unique and not nullable

Revision ID: 8983c7b4699d
Revises: 20d944622c86
Create Date: 2025-11-20 16:25:15.502299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8983c7b4699d'
down_revision: Union[str, None] = '20d944622c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Delete any existing codes with NULL email_restriction
    # Since we're making email_restriction mandatory, these codes are invalid
    op.execute("DELETE FROM registration_codes WHERE email_restriction IS NULL")

    op.alter_column('registration_codes', 'email_restriction',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_registration_codes_email_restriction'), table_name='registration_codes')
    op.create_index(op.f('ix_registration_codes_email_restriction'), 'registration_codes', ['email_restriction'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_codes_email_restriction'), table_name='registration_codes')
    op.create_index(op.f('ix_registration_codes_email_restriction'), 'registration_codes', ['email_restriction'], unique=False)
    op.alter_column('registration_codes', 'email_restriction',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
